# Generated by Cascade on 2025-11-22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("nutritionApp", "0003_fooditem_mobileotp_workout"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutCompletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("calories_kcal", models.DecimalField(decimal_places=1, max_digits=7)),
                ("completed_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="workout_completions", to="nutritionApp.customuser")),
                ("workout", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="completions", to="nutritionApp.workout")),
            ],
            options={
                "ordering": ["-completed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workoutcompletion",
            index=models.Index(fields=["user", "completed_at"], name="nutrition_user_co_0f5bf9_idx"),
        ),
        migrations.AddIndex(
            model_name="workoutcompletion",
            index=models.Index(fields=["workout", "completed_at"], name="nutrition_workout__9d5f45_idx"),
        ),
    ]
