# Generated by Django 5.2.7 on 2025-11-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutritionApp', '0004_workoutcompletion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workoutcompletion',
            new_name='nutritionAp_user_id_dd32c7_idx',
            old_name='nutrition_user_co_0f5bf9_idx',
        ),
        migrations.RenameIndex(
            model_name='workoutcompletion',
            new_name='nutritionAp_workout_41aec0_idx',
            old_name='nutrition_workout__9d5f45_idx',
        ),
    ]
